def getLinks():
    links=[]
    links.append("https://press.pirelli.com/2021-bahrain-grand-prix--sunday/")
    links.append("https://press.pirelli.com/2021-emilia-romagna-grand-prix--sunday/")
    links.append("https://press.pirelli.com/2021-portugal-grand-prix--sunday/")
    links.append("https://press.pirelli.com/2021-spanish-grand-prix---sunday/")
    links.append("https://press.pirelli.com/2021-monaco-grand-prix--sunday/")
    links.append("https://press.pirelli.com/2021-azerbaijan-grand-prix--sunday/")
    links.append("https://press.pirelli.com/2021-french-grand-prix---sunday/")
    links.append("https://press.pirelli.com/2021-styrian-grand-prix---sunday/")
    links.append("https://press.pirelli.com/2021-austrian-grand-prix--sunday/")
    links.append("https://press.pirelli.com/2021-british-grand-prix---sunday-0/")
    links.append("https://press.pirelli.com/2021-hungarian-grand-prix---sunday/")
    links.append("https://press.pirelli.com/2021-belgian-grand-prix---sunday/")
    links.append("https://press.pirelli.com/2021-dutch-grand-prix--sunday/")
    links.append("https://press.pirelli.com/2021-italian-grand-prix---sunday/")
    links.append("https://press.pirelli.com/2021-russian-grand-prix---sunday/")
    links.append("https://press.pirelli.com/2021-turkish-grand-prix---sunday/")
    links.append("https://press.pirelli.com/2021-united-states-grand-prix---sunday/")
    links.append("https://press.pirelli.com/2021-mexican-grand-prix--sunday/")
    links.append("https://press.pirelli.com/2021-brazilian-grand-prix----sunday/")
    links.append("https://press.pirelli.com/2021-qatar-grand-prix---sunday/")
    links.append("https://press.pirelli.com/2021-saudi-arabia-grand-prix---sunday/")
    links.append("https://press.pirelli.com/2021-abu-dhabi-grand-prix---sunday/")
    return links